const icons = [
  require("./icons/rocket-launch.svg"),
  require("./icons/cells.svg"),
  require("./icons/digital-camera.svg"),
  require("./icons/font.svg"),
  require("./icons/go-up.svg"),
  require("./icons/idea.svg"),
  require("./icons/letter.svg"),
  require("./icons/middle.svg"),
  require("./icons/top.svg"),
  require("./icons/verify.svg"),
  require("./icons/video-calling.svg"),
  require("./icons/link.svg"),
  require("./icons/font.svg"),
  // css
  require("./icons/mission.svg"),
  require("./icons/home-page.svg"),
  require("./icons/quill.svg"),
  require("./icons/paint-roller.svg"),
  require("./icons/settings.svg"),
  require("./icons/wireframe.svg"),
  require("./icons/unicorn.svg"),
  require("./icons/mission.svg"),
  require("./icons/right.svg"),
  require("./icons/blocking.svg"),
  require("./icons/bucket.svg"),
  require("./icons/font2.svg"),
  require("./icons/hat.svg"),
  require("./icons/home-page.svg"),
  require("./icons/keyboard.svg"),
  require("./icons/meteor.svg"),
  require("./icons/mystery.svg"),
  // javascript
  require("./icons/bicycle.svg"),
  require("./icons/boss.svg"),
  require("./icons/closed-umbrella.svg"),
  require("./icons/controls.svg"),
  require("./icons/decorative.svg"),
  require("./icons/edit.svg"),
  require("./icons/extraterrestrial.svg"),
  require("./icons/hat.svg"),
  require("./icons/id-card.svg"),
  require("./icons/maths.svg"),
  require("./icons/quote.svg"),
  require("./icons/robot-arm.svg"),
  require("./icons/smoke-pipe.svg"),
  require("./icons/superscript.svg"),
  require("./icons/technology.svg"),
  require("./icons/worker.svg"),
];

export default icons;
