export const CREATE_COURSE = "CREATE_COURSE";
export const UPDATE_COURSE = "UPDATE_COURSE";
export const CREATE_CHAPTER = "CREATE_CHAPTER";
export const CREATE_LESSON = "CREATE__LESSON";
export const UPDATE_CHAPTER = "UPDATE_CHAPTER";
export const UPDATE_LESSON = "UPDATE_LESSON";

// export const UPDATE_COURSE = "UPDATE_COURSE";
export const DELETE_COURSE = "DELETE_COURSE";
export const DELETE_USER = "DELETE_USER";
export const FETCH_ALL_COURSES = "FETCH_ALL_COURSES";
export const FETCH_ALL_USERS = "FETCH_ALL_USERS";

export const SET_COURSE_NAME = "SET_COURSE_NAME";
export const CHANGE_COURSE_NAME = "CHANGE_COURSE_NAME";
export const CHANGE_COURSE_DESCRIPTION = "CHANGE_COURSE_DESCRIPTION";

export const CHANGE_ACTUAL_COURSE = "CHANGE_ACTUAL_COURSE";
export const CHANGE_ACTUAL_CHAPTER = "CHANGE_ACTUAL_CHAPTER";

export const AUTH = "AUTH";
export const LOGOUT = "LOGOUT";
